export const t = {
  en: {
    nav: { dashboard: 'Dashboard', editor: 'Editor', gallery: 'Gallery', analytics: 'Analytics', finance: 'Finance', settings: 'Settings', help: 'Help', about: 'About', login: 'Login', register: 'Register', logout: 'Logout' },
    home: { hero: 'GridCraft — Collaborative Grid Editor', tagline: 'Build game levels together in real-time. AI suggestions, GPU simulation, and export pipeline.', cta: 'Open Editor' },
    dashboard: { title: 'Dashboard', levels: 'Levels Created', played: 'Levels Played', exports: 'Exports', session: 'Session Time', recent: 'Recent Activity', finance: 'Finance Journal', noActivity: 'No activity yet. Create your first level!', emptyJournal: 'No journal entries yet.' },
    editor: { title: 'Grid Editor', palette: 'Cell Palette', gridSize: 'Grid Size', undo: 'Undo', redo: 'Redo', simulate: 'Simulate', aiSuggest: 'AI Suggest', export: 'Export', clear: 'Clear Grid', aiThrottled: 'AI suggest available in {s}s', aiThinking: 'AI is suggesting...', aiReady: 'AI suggestion ready', simRunning: 'Simulation running...', simDone: 'Simulation complete: {coins} coins, {deaths} deaths, {time}ms', exportPng: 'Export as PNG', exportJson: 'Export as JSON', exportWebm: 'Export as WebM', copyShareLink: 'Copy Share Link', shareLinkCopied: 'Share link copied!', autosave: 'Auto-saved', collaboration: 'Collaborative Mode', usersOnline: 'users online', cellWall: 'Wall', cellFloor: 'Floor', cellSpike: 'Spike', cellCoin: 'Coin', cellExit: 'Exit', cellSpawn: 'Spawn', cellHazard: 'Hazard', balanceCheck: 'Balance Check', symmetrySuggest: 'Symmetry Suggest', flowOptimize: 'Flow Optimize' },
    gallery: { title: 'Level Gallery', search: 'Search levels...', difficulty: 'Difficulty', size: 'Grid Size', newest: 'Newest', mostPlayed: 'Most Played', mostLiked: 'Most Liked', empty: 'No levels found. Create one!', creator: 'Creator', played: 'Played', liked: 'Liked', share: 'Share', edit: 'Edit', like: 'Like' },
    analytics: { title: 'Analytics', trend: 'Level Creation Trend', distribution: 'Difficulty Distribution', heatmap: 'Session Heatmap', source: 'Traffic Sources (Attribution)', sessions: 'Session Breakdown', pageviews: 'Page Views', sourceNote: 'Source tracked via URL params (UTM) and localStorage. No third-party trackers.' },
    finance: { title: 'Finance Journal', entries: 'Journal Entries', total: 'Total Value', catCreative: 'Creative Output', catSimulation: 'Simulation Credits', catExport: 'Export Fees', empty: 'No journal entries. Every export creates a journal entry.' },
    settings: { title: 'Settings', language: 'Language', theme: 'Theme', themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System', gridDefault: 'Default Grid Size', autosaveInterval: 'Auto-save Interval (seconds)', about: 'About' },
    help: { title: 'Help', editorGuide: 'Editor Guide', legend: 'Grid Legend', shortcuts: 'Keyboard Shortcuts', shortcutsList: 'Z: Undo, Y: Redo, S: Simulate, E: Export, 1-7: Select cell, Click: Place, Drag: Paint' },
    about: { title: 'About', version: 'Version', techStack: 'Tech Stack', attribution: 'Attribution', builtBy: 'Built with Next.js 16 + TypeScript + Tailwind v4 + shadcn/ui', github: 'View on GitHub' },
    auth: { login: 'Login', register: 'Register', email: 'Email', password: 'Password', confirm: 'Confirm Password', submit: 'Submit', cancel: 'Cancel', error: 'Invalid email or password', success: 'Success', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', logout: 'Logout' },
    toast: { saved: 'Saved', copied: 'Copied', error: 'Error', success: 'Success' }
  },
  id: {
    nav: { dashboard: 'Dasbor', editor: 'Editor', gallery: 'Galeri', analytics: 'Analitik', finance: 'Keuangan', settings: 'Pengaturan', help: 'Bantuan', about: 'Tentang', login: 'Masuk', register: 'Daftar', logout: 'Keluar' },
    home: { hero: 'GridCraft — Editor Grid Kolaboratif', tagline: 'Bangun level game bersama secara real-time. Sugesti AI, simulasi GPU, dan pipeline ekspor.', cta: 'Buka Editor' },
    dashboard: { title: 'Dasbor', levels: 'Level Dibuat', played: 'Level Dimainkan', exports: 'Ekspor', session: 'Waktu Sesi', recent: 'Aktivitas Terbaru', finance: 'Jurnal Keuangan', noActivity: 'Belum ada aktivitas. Buat level pertama!', emptyJournal: 'Belum ada entri jurnal.' },
    editor: { title: 'Editor Grid', palette: 'Palette Sel', gridSize: 'Ukuran Grid', undo: 'Batal', redo: 'Ulang', simulate: 'Simulasi', aiSuggest: 'Suggest AI', export: 'Ekspor', clear: 'Hapus Grid', aiThrottled: 'Suggest AI tersedia dalam {s}d', aiThinking: 'AI menyarankan...', aiReady: 'Saran AI siap', simRunning: 'Simulasi berjalan...', simDone: 'Simulasi selesai: {coins} koin, {deaths} kematian, {time}ms', exportPng: 'Ekspor PNG', exportJson: 'Ekspor JSON', exportWebm: 'Ekspor WebM', copyShareLink: 'Salin Link Bagikan', shareLinkCopied: 'Link disalin!', autosave: 'Disimpan otomatis', collaboration: 'Mode Kolaborasi', usersOnline: 'pengguna online', cellWall: 'Dinding', cellFloor: 'Lantai', cellSpike: 'Tajam', cellCoin: 'Koin', cellExit: 'Keluar', cellSpawn: 'Spawn', cellHazard: 'Bahaya', balanceCheck: 'Cek Keseimbangan', symmetrySuggest: 'Saran Simetri', flowOptimize: 'Optimasi Alur' },
    gallery: { title: 'Galeri Level', search: 'Cari level...', difficulty: 'Kesulitan', size: 'Ukuran Grid', newest: 'Terbaru', mostPlayed: 'Paling Dimainkan', mostLiked: 'Paling Disukai', empty: 'Tidak ada level. Buat satu!', creator: 'Pembuat', played: 'Dimainkan', liked: 'Disukai', share: 'Bagikan', edit: 'Edit', like: 'Sukai' },
    analytics: { title: 'Analitik', trend: 'Tren Pembuatan Level', distribution: 'Distribusi Kesulitan', heatmap: 'Peta Panas Sesi', source: 'Sumber Traffic (Attribution)', sessions: 'Breakdown Sesi', pageviews: 'Halaman Dilihat', sourceNote: 'Sumber dilacak via URL params (UTM) dan localStorage. Tanpa pelacak pihak ketiga.' },
    finance: { title: 'Jurnal Keuangan', entries: 'Entri Jurnal', total: 'Total Nilai', catCreative: 'Output Kreatif', catSimulation: 'Kredit Simulasi', catExport: 'Biaya Ekspor', empty: 'Tidak ada entri jurnal. Setiap ekspor membuat entri jurnal.' },
    settings: { title: 'Pengaturan', language: 'Bahasa', theme: 'Tema', themeLight: 'Terang', themeDark: 'Gelap', themeSystem: 'Sistem', gridDefault: 'Ukuran Grid Default', autosaveInterval: 'Interval Auto-save (detik)', about: 'Tentang' },
    help: { title: 'Bantuan', editorGuide: 'Panduan Editor', legend: 'Legenda Grid', shortcuts: 'Pintasan Keyboard', shortcutsList: 'Z: Batal, Y: Ulang, S: Simulasi, E: Ekspor, 1-7: Pilih sel, Klik: Tempatkan, Drag: Cat' },
    about: { title: 'Tentang', version: 'Versi', techStack: 'Tech Stack', attribution: 'Atribusi', builtBy: 'Dibangun dengan Next.js 16 + TypeScript + Tailwind v4 + shadcn/ui', github: 'Lihat di GitHub' },
    auth: { login: 'Masuk', register: 'Daftar', email: 'Email', password: 'Kata Sandi', confirm: 'Konfirmasi', submit: 'Kirim', cancel: 'Batal', error: 'Email atau kata sandi tidak valid', success: 'Berhasil', noAccount: 'Belum punya akun?', hasAccount: 'Sudah punya akun?', logout: 'Keluar' },
    toast: { saved: 'Disimpan', copied: 'Disalin', error: 'Kesalahan', success: 'Berhasil' }
  }
} as const

export type TKey = typeof t.en
